export interface ExecuteParityDeps {
  symbol: string;
  freshSignal: any;
  longPos: any | null | undefined;
  shortPos: any | null | undefined;
  parityResult: any;

  openPos: (side: 'LONG' | 'SHORT', signal?: any, sizeOverride?: number) => Promise<void>;
  partialClosePos: (pos: any, fraction: number, reason: string) => Promise<void>;
  closePos: (pos: any, reason: string) => Promise<void>;
  addLog: (msg: string) => void;
}

export async function executeParityPaperDecision(deps: ExecuteParityDeps): Promise<boolean> {
  const {
    symbol,
    freshSignal,
    longPos,
    shortPos,
    parityResult,
    openPos,
    partialClosePos,
    closePos,
    addLog,
  } = deps;

  const action = String(parityResult?.final_action || 'HOLD');
  const op = parityResult?.operational_action || null;
  const reason = parityResult?.why_blocked
    ? `Parity Blocked: ${parityResult.why_blocked}`
    : `Parity Allowed: ${parityResult?.why_allowed || 'Standard Execution'}`;

  switch (action) {
    // Note: OPEN_LONG and OPEN_SHORT are runtime-only execution actions.
    // They are not part of the canonical parity contract (which focuses on
    // managing existing structures like ADD_0.5_LONG, REDUCE_0.5_SHORT, etc.).
    // They are generated by deriveRequestedAction when Structure === 'NONE'.
    case 'OPEN_LONG':
      await openPos('LONG', freshSignal);
      addLog(`[PARITY_V2] ${symbol} -> OPEN_LONG | ${reason}`);
      return true;

    case 'OPEN_SHORT':
      await openPos('SHORT', freshSignal);
      addLog(`[PARITY_V2] ${symbol} -> OPEN_SHORT | ${reason}`);
      return true;

    case 'LOCK_NEUTRAL':
      if (longPos && !shortPos) {
        await openPos('SHORT', null, longPos.size);
      } else if (shortPos && !longPos) {
        await openPos('LONG', null, shortPos.size);
      }
      addLog(`[PARITY_V2] ${symbol} -> LOCK_NEUTRAL | ${reason}`);
      return true;

    case 'ADD_0.5_LONG':
      if (longPos) {
        await openPos('LONG', freshSignal, longPos.size * 0.5);
        addLog(`[PARITY_V2] ${symbol} -> ADD_0.5_LONG | ${reason}`);
        return true;
      }
      return false;

    case 'ADD_0.5_SHORT':
      if (shortPos) {
        await openPos('SHORT', freshSignal, shortPos.size * 0.5);
        addLog(`[PARITY_V2] ${symbol} -> ADD_0.5_SHORT | ${reason}`);
        return true;
      }
      return false;

    case 'REDUCE_0.5_LONG':
      if (longPos) {
        await partialClosePos(longPos, 0.5, 'Parity Reduce Long');
        addLog(`[PARITY_V2] ${symbol} -> REDUCE_0.5_LONG | ${reason}`);
        return true;
      }
      return false;

    case 'REDUCE_0.5_SHORT':
      if (shortPos) {
        await partialClosePos(shortPos, 0.5, 'Parity Reduce Short');
        addLog(`[PARITY_V2] ${symbol} -> REDUCE_0.5_SHORT | ${reason}`);
        return true;
      }
      return false;

    case 'UNLOCK':
      if (shortPos && (shortPos.currentPnl || 0) > 0) {
        await closePos(shortPos, 'Parity Unlock');
        addLog(`[PARITY_V2] ${symbol} -> UNLOCK short | ${reason}`);
        return true;
      }
      if (longPos && (longPos.currentPnl || 0) > 0) {
        await closePos(longPos, 'Parity Unlock');
        addLog(`[PARITY_V2] ${symbol} -> UNLOCK long | ${reason}`);
        return true;
      }
      return false;

    case 'FULL_CYCLE_EXIT':
      if (longPos) await closePos(longPos, 'Parity Full Cycle Exit');
      if (shortPos) await closePos(shortPos, 'Parity Full Cycle Exit');
      addLog(`[PARITY_V2] ${symbol} -> FULL_CYCLE_EXIT | ${reason}`);
      return true;

    case 'REVERT_TO_1TO1':
      if (op === 'REDUCE_0.5_LONG' && longPos) {
        await partialClosePos(longPos, 0.5, 'Parity Revert to 1:1');
        addLog(`[PARITY_V2] ${symbol} -> REVERT_TO_1TO1 via REDUCE_0.5_LONG | ${reason}`);
        return true;
      }
      if (op === 'REDUCE_0.5_SHORT' && shortPos) {
        await partialClosePos(shortPos, 0.5, 'Parity Revert to 1:1');
        addLog(`[PARITY_V2] ${symbol} -> REVERT_TO_1TO1 via REDUCE_0.5_SHORT | ${reason}`);
        return true;
      }
      return false;

    case 'HOLD':
    case 'WAIT_AND_SEE':
    case 'BLOCK_EXPANSION':
    case 'TAKE_PROFIT_DEFENSIVE':
    case 'PROTECTIVE_STOP_GREEN_LEG':
    default:
      addLog(`[PARITY_V2] ${symbol} -> ${action} | ${reason}`);
      return false;
  }
}
