// Signal Payload Verification Gate — Type Definitions
// Phase 1: Canonical types for gate verdict, issue codes, and Sentinel rules.

// ---------------------------------------------------------------------------
// 1. Gate Verdict
// ---------------------------------------------------------------------------

export enum GateVerdict {
  PASS = 'PASS',
  WARN = 'WARN',
  FAIL = 'FAIL',
  INSUFFICIENT = 'INSUFFICIENT',
}

// ---------------------------------------------------------------------------
// 2. Gate Issue Codes
// ---------------------------------------------------------------------------

export enum GateIssueCode {
  MISSING_FIELD = 'MISSING_FIELD',
  EMPTY_VALUE = 'EMPTY_VALUE',
  ENUM_DRIFT = 'ENUM_DRIFT',
  SHAPE_MISMATCH = 'SHAPE_MISMATCH',
  TYPE_MISMATCH = 'TYPE_MISMATCH',
  MAPPING_GAP = 'MAPPING_GAP',
  GOLDEN_RULE_CONFLICT = 'GOLDEN_RULE_CONFLICT',
  MR_BLOCK_CONDITION = 'MR_BLOCK_CONDITION',
  RECOVERY_SUSPENDED_CONDITION = 'RECOVERY_SUSPENDED_CONDITION',
  AMBIGUOUS_INPUT = 'AMBIGUOUS_INPUT',
  INSUFFICIENT_CONTEXT = 'INSUFFICIENT_CONTEXT',
  RECLASSIFICATION_PENDING = 'RECLASSIFICATION_PENDING',
}

// ---------------------------------------------------------------------------
// 3. Sentinel Rules
// ---------------------------------------------------------------------------

export enum SentinelRule {
  GOLDEN_RULE = 'GOLDEN_RULE',
  MR_GUARD = 'MR_GUARD',
  RECOVERY_SUSPENDED = 'RECOVERY_SUSPENDED',
  AMBIGUITY_BLOCK = 'AMBIGUITY_BLOCK',
  RECLASSIFICATION_INTEGRITY = 'RECLASSIFICATION_INTEGRITY',
}

// ---------------------------------------------------------------------------
// 4. Canonical Value Sets (runtime validation)
// ---------------------------------------------------------------------------

export const VALID_PRIMARY_TREND_4H = ['UP', 'DOWN', 'UNCLEAR'] as const;
export type PrimaryTrend4H = (typeof VALID_PRIMARY_TREND_4H)[number];

export const VALID_TREND_STATUS = [
  'CONTINUATION_CONFIRMED',
  'REVERSAL_WATCH',
  'REVERSAL_CONFIRMED_STRONG',
  'CHOP',
] as const;
export type TrendStatus = (typeof VALID_TREND_STATUS)[number];

export const VALID_STRUCTURE = [
  'NONE',
  'SINGLE',
  'LOCK_1TO1',
  'LONG_1P5_SHORT_1',
  'SHORT_1P5_LONG_1',
  'LONG_2_SHORT_1',
  'SHORT_2_LONG_1',
] as const;
export type Structure = (typeof VALID_STRUCTURE)[number];

export const VALID_HEDGE_LEG_STATUS = [
  'NONE',
  'HEDGE_FULL',
  'RESIDUAL_OPPOSING_LEG',
] as const;
export type HedgeLegStatus = (typeof VALID_HEDGE_LEG_STATUS)[number];

export const VALID_CONTEXT_MODE = [
  'CONTINUATION_RECOVERY',
  'REVERSAL_DEFENSE',
  'LOCK_WAIT_SEE',
  'EXIT_READY',
  'RISK_DENIED',
] as const;
export type ContextMode = (typeof VALID_CONTEXT_MODE)[number];

export const VALID_RISK_OVERRIDE = [
  'NONE',
  'MR_BLOCK',
  'RECOVERY_SUSPENDED',
  'AMBIGUITY_BLOCK',
] as const;
export type RiskOverride = (typeof VALID_RISK_OVERRIDE)[number];

export const VALID_STRUCTURE_ORIGIN = [
  'HEDGE_TRIGGER',
  'EXPANSION',
  'REVERT',
  'INITIAL',
] as const;
export type StructureOrigin = (typeof VALID_STRUCTURE_ORIGIN)[number];

export const VALID_ACTIONS = [
  'HOLD',
  'LOCK_NEUTRAL',
  'TAKE_PROFIT_DEFENSIVE',
  'ADD_0.5_LONG',
  'ADD_0.5_SHORT',
  'REDUCE_0.5_LONG',
  'REDUCE_0.5_SHORT',
  'UNLOCK',
  'REVERT_TO_1TO1',
  'FULL_CYCLE_EXIT',
  'PROTECTIVE_STOP_GREEN_LEG',
  'BLOCK_EXPANSION',
  'WAIT_AND_SEE',
  // Runtime-only execution actions generated by deriveRequestedAction() in
  // parity_runtime.ts when Structure === 'NONE'. Not part of the canonical
  // parity contract for existing structures, but valid runtime values.
  'OPEN_LONG',
  'OPEN_SHORT',
] as const;
export type ParityActionCanonical = (typeof VALID_ACTIONS)[number];

// ---------------------------------------------------------------------------
// 5. GateIssue
// ---------------------------------------------------------------------------

export interface GateIssue {
  code: GateIssueCode;
  severity: 'low' | 'medium' | 'high';
  path: string;
  message: string;
  expected?: any;
  actual?: any;
}

// ---------------------------------------------------------------------------
// 6. GateResult
// ---------------------------------------------------------------------------

export interface GateResult {
  verificationStatus: GateVerdict;
  safeToEvaluateInParity: boolean;
  issues: GateIssue[];
  sentinelRuleAtRisk: SentinelRule[];
  summary: {
    symbol: string;
    market: string;
    timeframe: string;
  };
  auditHints: {
    whySafe: string[];
    whyBlocked: string[];
  };
  timestamp: string;
}
